WIDTH, HEIGHT = 1920, 1080
VELOCITY = 6
GRAVITY = 8
JUMP_VELOCITY = 20

PLAYER_WIDTH = 46
PLAYER_HEIGHT = 64
PLAYER_STARTING_POSITION_X_AXIS = WIDTH // 2
PLAYER_STARTING_POSITION_Y_AXIS = 440

WALL_WIDTH, WALL_HEIGHT = 50, 1080
FLOOR_WIDTH, FLOOR_HEIGHT = 550, 50
LEFT_EDGE_OF_PLAY_AREA = 710
RIGHT_EDGE_OF_PLAY_AREA = 1210

LOG_FUNCTION_CALLS = False
LOG_KEY_INPUTS = False

SMALL_PLATFORM_WIDTH = 64
SMALL_PLATFORM_HEIGHT = 15

SCROLL_SPEED = 2