WIDTH, HEIGHT = 1920, 1080
VELOCITY = 6
GRAVITY = 8
JUMP_VELOCITY = 20
jump_start_time = 0
playerAnimationCounter = 0 

PLAYER_WIDTH = 46
PLAYER_HEIGHT = 64
PLAYER_STARTING_POSITION_X_AXIS = WIDTH // 2
PLAYER_STARTING_POSITION_Y_AXIS = 440